#### Bert Model:
Bert model is a transformer based model which uses self attention layer.
It is used to convert words into vectors in such a way so that their semantic and contextual meaning is preserved.
before applying the bert model, we have to pre process the data to be able to feed that data into the bert model.

In [1]:
# importing the dependencies
#!pip install tensorflow_hub
#!pip install tensorflow_text
import tensorflow_hub as hub
import tensorflow_text as text

Different versions of the BERT model can be downloaded from the tensorflow hub website.
https://tfhub.dev/google/collections/bert/1

In [2]:
preprocessed_url='https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3'
encoder_url='https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4'

In [3]:
bert_preprocessed_model=hub.KerasLayer(preprocessed_url)

In [4]:
text=['Nice Movie Indeed','I love Deep Learning']

#### Preprocessing model:
This is used to convert text into a certain format so that can be processed by the bert model. it automatically converts words into vectors by applying several prprocessing steps.
this preprocessing involves:

a) tokenization

b) adding tokens to mark the beginning and ending of the sentences.

c) Padding

d) assigning unique integer id to each word.

In [8]:

output=bert_preprocessed_model(text)

In [9]:
type(output)

dict

In [13]:
output.keys()

dict_keys(['input_type_ids', 'input_word_ids', 'input_mask'])

In [18]:
output['input_mask'] # it adds two more tokens to the beginning and the end of the sentence

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [20]:
output['input_word_ids'] # assigning the index to each word in the vocabulary.

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[ 101, 3835, 3185, 5262,  102,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0],
       [ 101, 1045, 2293, 2784, 4083,  102,    0,    0,    0,    0,    0,
           0,

#### Bert Encoder:
now we can use the encoder after processing the input.

In [21]:
bert_model=hub.KerasLayer(encoder_url)

In [22]:
bert_output=bert_model(output)

In [23]:
bert_output.keys()

dict_keys(['sequence_output', 'pooled_output', 'encoder_outputs', 'default'])

In [24]:
#Examining the output of the bert model
bert_output['pooled_output']


<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.791774  , -0.21411902,  0.49769545, ...,  0.24465242,
        -0.47334465,  0.8175868 ],
       [-0.7819546 , -0.20902902,  0.5304151 , ...,  0.31390852,
        -0.60525256,  0.8173208 ]], dtype=float32)>

#### Pooled_output vs Sequence_Output:
Pooled_output gives the embedding of the whole sentence. Whereas, Sequence_output gives the embedding of each word.

In [25]:
bert_output['sequence_output']


<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 7.2920412e-02,  8.5678160e-02,  1.4476837e-01, ...,
         -9.6770801e-02,  8.7221146e-02,  7.7111028e-02],
        [ 1.7839377e-01, -1.9006082e-01,  5.0349444e-01, ...,
         -5.8698267e-02,  3.2717147e-01, -1.5578502e-01],
        [ 1.8701456e-01, -4.3388769e-01, -4.8875162e-01, ...,
         -1.5502810e-01,  1.4513135e-03, -2.4470958e-01],
        ...,
        [ 1.2083077e-01,  1.2884237e-01,  4.6453524e-01, ...,
          7.3755175e-02,  1.7441934e-01,  1.6522089e-01],
        [ 7.9678386e-02, -1.1906989e-02,  5.0225419e-01, ...,
          1.3777757e-01,  2.1002182e-01,  6.2461002e-03],
        [-7.2127059e-02, -2.8303489e-01,  5.9033322e-01, ...,
          4.7551912e-01,  1.6668460e-01, -8.9203194e-02]],

       [[ 9.3838871e-02,  2.9481417e-02, -4.5924336e-02, ...,
         -9.9129155e-02,  3.3907592e-05,  2.1539062e-01],
        [ 7.6166362e-01, -3.7808530e-02,  4.7379714e-02, ...,
         -5.5204666e-01,  5.

In [26]:
len(bert_output['encoder_outputs'])
# This length is 12 because we are using bert base model in which there are 12 encoders.

12